# -*- coding: utf-8 -*-
"""Breast cancer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1490XtvUYEs7kQ8w-_y4r6qNXpLFiJXXU

Breast cancer

The workflow for the probelm is
Probelm Statement--> Data collection--> Data analysis and Vis--> Data preprocesssing--> Model selection & training--> Optimization--> inference

###1) Install and importing the required dependencies
"""

!pip install -q numpy pandas matplotlib seaborn scikit-learn

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns


from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, classification_report
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler

"""###2) Loading the data set"""

df=pd.read_csv("/content/breast_cancer_dataset.csv")

df.head()

df.info()

## we will be dropping the id like column as it has no relarion with the target and the features
df.drop(columns=["id"])

"""based on the basic data overview we can see that there is no category column that describe the relation to the target and we have dropped the id like column the main reason is that the id like columns can cause the model to think if this id number comes into the pic than this person has the breast cancer but in real life scenario the person doesn't have lol

as we are done with the basic info of the data set now we are going to begin with the eda/data qulaity check

###3) Data quality check(EDA)
"""

df.head()

df.shape

##1 basic info that we have already done in the loading data set

##2 we are going separate the categorical and the numerical columns in the data set and in our data set we have the categorcal column as diagnosis and we are going to map with 0 and 1

df["diagnosis"]=df["diagnosis"].map({"M":0, "B":1})

df.head()

##3 we are going to check is there any not null values are there or not in the data set
df.isna().sum()

"""there is no not null values means there is no missing values in the data set

"""

###4 we are going to check is there any kind of the encoded values in the data set or no

for cols in df.columns:
  c=df[cols].value_counts()
  print(c)

"""ok there is no values that is encoded in the data set


"""

##5 we are going to check is there any kind of duplicates column is yes than we are going to drop that
df.duplicated().sum(

)

"""there is no duplicates column in the data set"""

##6 we are going to check is there any kind of the constant and the quasi constant columns are there in the data set or no

## checking is there any constant columns in the data set or not
colum= df.nunique()
length= len(df)
const_col= colum[colum==1].index.tolist()
print(const_col)

"""there is no constant columns in the data set"""

## checking for the quasi constant columns in the data set or not

c=[] ## columns likely to be quasi constant
for column in df.columns:
  tot_value=df[column].value_counts(normalize=True).values[0]
  if tot_value>0.85 and tot_value not in const_col:
    c.append(tot_value)
print(c)

"""there is no quasi constant columns in the data set"""

##7 as we have already dropped the id like columns

##8 we are going to check for the high zero columns in the data set
colls=[]
for high_zero_col in df.columns:
  zero_count=(df[high_zero_col]==0).sum()
  lenght= zero_count/len(df[high_zero_col])

  if lenght>0.85:
    colls.append(lenght)

print(colls)

"""there is no high zero columns in the data set

we are at the end of the data set analysis and everthing is good and now we can visuvalize the same in the plots

###4 Data vis
"""

## as we are going to perfrom the univarative, bivarative and mutlivarative analysis for the data set
## important note is that we don't have any categorical columns in the data set we need to play around using only the numerical data set

df_num= df.copy(deep=True)

df.head()

## univarative analysis
df.skew(

)

"""likely to have a positive skew"""

df_num.kurt()

## using the hist plot

for hist_plot in df_num:
  plt.figure(figsize=(5,3))
  sns.histplot(x=df[hist_plot], kde=True)
  plt.xlabel(hist_plot)
  plt.title("Histplot for the numerical data")
  plt.show()

## as now we are going to check for the boxplot

for box_plot in df_num:
  plt.figure(figsize=(5,3))
  sns.boxplot(x=df[box_plot])
  plt.xlabel(box_plot)
  plt.title("box-plot")
  plt.show(

  )

"""there is an slightly outliers are there in the data set and now we are done with the univarative note is that slightly tends to postivie skew and outliers"""

## Bivarative analysis in this we are going to perform only for the num vs num using the scatter plot

for i,scatter1 in enumerate(df_num.columns):
  for j, scatter2 in enumerate(df_num.columns):
    if i<j:
      plt.figure(figsize=(5,3))
      sns.scatterplot(x=df_num[scatter1], y=df_num[scatter2])
      plt.xlabel(scatter1)
      plt.ylabel(scatter2)
      plt.title("scatterplot")
      plt.show()

## as we are done with the bivarativ analysis and now we are going to multivarativ analysis

##mutlivarative analysis

plt.figure(figsize=(6,4))
sns.heatmap(
    df.corr(),
    cmap="coolwarm"
)
plt.title("heatmap")
plt.show()

"""as we are done with our data quality check and the data viz now we are proceedin with the data preprocessing

###5 Data preprocessing
"""

## in this data preprocessig we are going to separate the xtrain xtest y train and y test

x=df_num.drop(columns=["diagnosis"])
y=df_num["diagnosis"]

x.head()

y.head()

x_train, x_test, y_train, y_test= train_test_split(
    x,
    y,
    stratify=y,
    test_size=0.2,
    random_state=42
)

x_train.head()

x_test.head()

y_train.head()

## we are good to go with the model selection and the training as in the preprocessing steps we can check for the outliers are there or not in the data ser

x_train_copy= x_train.copy(deep=True)
x_test_copy=x_test.copy(deep=True)
y_test_copy=y_test.copy(deep=True)
y_train_copy=y_train.copy(deep=True)

for col in x_train_copy.columns:
    q1 = x_train_copy[col].quantile(0.25)
    q3 = x_train_copy[col].quantile(0.75)
    iqr = q3 - q1

    lower_bound = q1 - 1.5 * iqr
    upper_bound = q3 + 1.5 * iqr

    x_train_copy = x_train_copy[(x_train_copy[col] >= lower_bound) & (x_train_copy[col] <= upper_bound)]

x_train_copy.head()

"""###6 Model selection"""

scaler=StandardScaler()

x_train_scale=scaler.fit_transform(x_train)
x_test_scale=scaler.transform(x_test)

model=LogisticRegression()

model.fit(x_train_scale, y_train)

##score on trainig model

model.score(x_train_scale,y_train)

model.score(x_test_scale,y_test)

"""###7 Model optimization"""

## we will be using multiple models to check which is more optimal
from sklearn.decomposition import PCA
from sklearn.svm import SVC
pipeline=Pipeline(
    [
        ("scaler",StandardScaler()),
        ("pca",PCA()),
        ("model",SVC(kernel="rbf"))

    ]
)

# grid of hyperparameters
param_grid = [
    {
        "pca__n_components": [10, 15, 20, 25, 30],
        "model__C": [0.1, 1, 10, 100, 1000],
        "model__gamma": [0.001, 0.01, 0.1, 1, "scale"]
    }
]

# cross-validation setup (used inside grid search cv)
from sklearn.model_selection import StratifiedKFold, GridSearchCV
RANDOM_STATE=42
k=5
skf = StratifiedKFold(n_splits=k, shuffle=True, random_state=RANDOM_STATE)

from sklearn.pipeline import Pipeline
from sklearn.model_selection import GridSearchCV

grid_search = GridSearchCV(
    estimator=pipeline,
    param_grid=param_grid,
    scoring="recall",
    cv=skf,
    n_jobs=-1
)

grid_search.fit(x_train,y_train)

print("Best params:", grid_search.best_params_)
print("Best score:", grid_search.best_score_)

best_pipeline = Pipeline(
    [
        ("scaler", StandardScaler()),
        ("pca", PCA(n_components=10)),
        ("model", SVC(kernel="rbf", C=10, gamma="scale"))
    ]
)

# train the pipeline
best_pipeline.fit(x_train, y_train)

"""###8 Evaluvation"""

y_train_pred= best_pipeline.predict(x_train)

train_acc = accuracy_score(y_train, y_train_pred)
print(f"Training Accuracy: {round(train_acc*100, 2)} %")

y_test_pred= best_pipeline.predict(x_test)

test_accs= accuracy_score(y_test, y_test_pred)
print(f"Test accuracy: {round(test_accs*100,2)}%")

"""###9 Building an predictive system on it

"""

def predict_cancer(input_features):
    input_df = pd.DataFrame(
        [input_features],
        columns=x_train.columns
    )
    prediction = best_pipeline.predict(input_df)
    print("Model prediction:", prediction)
    if prediction[0] == 1:
        print("Diagnosis - Malignant 🔴")
    else:
        print("Diagnosis - Benign 🟢")

x_test.head()

test_1 = x_test.iloc[80].tolist()
print(test_1)

predict_cancer(test_1)

test_2= x_test.iloc[70].tolist()
print(test_2)

predict_cancer(test_2)

